# Webserver configs
server:
  port: 8081

spring:
  #Datasource connection details
  datasource:
    url: jdbc:mysql://localhost:10002/intern_db
    username: user
    password: password

  #JPA schema generation
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: create-drop #for fine-grained control on ddl
    show-sql: true
  #JPA generating SQL underneath.
  properties:
    hibernate.format_sql: true
    hibernate.use_sql_comments: true